apiVersion: v1
kind: Service

metadata:
  name: gearapp-service
  labels:
    app: gearapp

spec:
  selector:
    app: gearapp


  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
